### ISSUE TITLE
Cannot load from short array because "sun.awt.FontConfiguration.head" is null

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/GridExporterAddon#15]
I'm facing this problem when deploying a demo application using the addon using docker:

```
Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
        at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
        at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224)
        at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:106)
        at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706)
        at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:358)
        at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:315)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:315)
        at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
        ... 61 more
```

I suspect that it is related to a missing font in the OS

**Comment by mlopezFC** [comment]
Fixed with [this](https://github.com/docker-library/openjdk/issues/73#issuecomment-451102068) approach.
